import Link from "next/link";
import { AlertTriangle, ArrowRight, Check, CircleHelp, Info, Network, ShieldAlert } from "lucide-react";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

export default function DocsPage() {
  return <main><SiteHeader />
    <div className="docs-shell">
      <aside className="docs-nav"><span>GET STARTED</span><a href="#overview">Overview</a><a href="#quick-start">Quick start</a><a href="#creating-a-rule">Create a rule</a><span>ROUTING</span><a href="#automatic-routing">Automatic routing</a><a href="#manual-proxy">Manual proxy</a><a href="#strict-mode">Strict Mode</a><span>REFERENCE</span><a href="#architecture">Architecture</a><a href="#limitations">Known limitation</a><a href="#uninstall">Uninstall</a></aside>
      <article className="docs-content">
        <div className="docs-intro" id="overview"><div className="section-kicker">DOCUMENTATION</div><h1>Get started with NetRoute</h1><p>Learn how to route individual Windows applications through specific network adapters, understand the two routing paths, and choose the right protection for each rule.</p><div className="docs-pills"><span>Windows 10/11</span><span>64-bit</span><span>v1.0.0</span></div></div>
        <section id="quick-start"><h2>Quick start</h2><p>NetRoute’s installer adds both the desktop app and the background routing service.</p><ol className="steps"><li><b>1</b><div><strong>Install NetRoute</strong><p>Download and run <code>NetRoute-Setup.exe</code>. Approve the administrator prompt so Windows can register the service.</p></div></li><li><b>2</b><div><strong>Open Applications</strong><p>In NetRoute, choose Applications and select the executable you want to route.</p></div></li><li><b>3</b><div><strong>Choose an adapter</strong><p>Assign Wi-Fi, Ethernet, a USB-tethered phone, or another active adapter.</p></div></li><li><b>4</b><div><strong>Apply the rule</strong><p>Enable Strict Mode if the app must never fall back to Windows’ default connection.</p></div></li></ol></section>
        <section id="creating-a-rule"><h2>Create a routing rule</h2><p>Rules match a Windows executable to one adapter. From <strong>Applications</strong>, add the executable, select the assigned adapter, choose whether the rule is strict, then apply it.</p><div className="callout info"><Info/><div><strong>Tip</strong><p>Close existing connections or restart the target app after creating a rule so new connections use the selected route.</p></div></div></section>
        <section id="automatic-routing"><h2>Automatic routing</h2><p>The automatic path uses WinDivert to detect a matched app’s new connection and redirect it through the selected adapter. It requires no proxy setting inside the target app, making it the easiest option for browsers, games, and tools without proxy controls.</p><div className="docs-table"><div><span>Setup</span><strong>None inside the app</strong></div><div><span>Coverage</span><strong>Matched application traffic</strong></div><div><span>Precision</span><strong>Best-effort on a brand-new destination</strong></div></div></section>
        <section id="manual-proxy"><h2>Manual proxy</h2><p>For applications with their own HTTP/HTTPS proxy setting, NetRoute exposes a local proxy address for each adapter. Enter the address shown in the selected rule, for example <code>127.0.0.1:28184</code>.</p><p>Because NetRoute creates the outbound connection itself, the route is correct from its first packet. This is the recommended path for download managers and any task where a first-attempt timeout matters.</p><div className="callout success"><Check/><div><strong>Use manual proxy when</strong><p>The app supports a proxy and you want the most reliable first-connection behavior available in v1.0.</p></div></div></section>
        <section id="strict-mode"><h2>Strict Mode</h2><p>Strict Mode prevents accidental fallback. If the assigned adapter disconnects, the application is blocked instead of moving to the default Windows route.</p><div className="callout warning"><ShieldAlert/><div><strong>Expected behavior</strong><p>The app may show an offline or connection error until its assigned adapter returns. That block is the rule working as intended.</p></div></div></section>
        <section id="architecture"><h2>How NetRoute runs</h2><div className="architecture-doc"><article><Network/><strong>NetRoute.App</strong><p>The WPF interface provides the dashboard, rule editor, settings, and system tray controls.</p></article><ArrowRight/><article><Network/><strong>Routing Service</strong><p>The Windows Service performs routing and keeps enforcing active rules independently of the window.</p></article></div></section>
        <section id="limitations"><h2>Known limitation</h2><div className="callout caution"><AlertTriangle/><div><strong>Automatic routing is best-effort</strong><p>Windows can send the first packet of a brand-new connection before NetRoute’s user-mode code finishes reacting to the kernel notification. That first attempt can occasionally time out. A retry—automatic in most apps—then works, and later connections to the same destination are unaffected.</p></div></div><p>Full automatic first-packet precision would require a signed Windows Filtering Platform kernel driver. Until then, use the manual proxy path where the first attempt must be exact.</p></section>
        <section id="uninstall"><h2>Uninstall</h2><p>Open <strong>Settings → Apps → NetRoute → Uninstall</strong>. The uninstaller stops and removes the routing service, shortcuts, and installed files.</p></section>
        <div className="docs-end"><CircleHelp/><div><strong>Still have a question?</strong><p>Check the repository for release notes and open issues.</p></div><a href="https://github.com/Heygoodbye/NetRoute" target="_blank" rel="noreferrer">Open GitHub <ArrowRight size={15}/></a></div>
      </article>
    </div><SiteFooter />
  </main>;
}
